version: '0.10.1-{build}'

os: Visual Studio 2017
clone_folder: C:\USBqemu-wheel
clone_depth: 3
test: off
skip_non_tags: true

platform:
 - Win32
 - x64

configuration:
 - Release
 - RelWithDebInfo

before_build:
 - ps: $env:Date="$(git show -s --date=short --format='%ad')"
 - cmd: mkdir build
 - cmd: cd build
 - cmake -A %platform% ..

build_script:
 - cmake --build . --config %configuration% -- /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

install:
 - set COMMIT_SHA=%APPVEYOR_REPO_COMMIT:~0,8%

artifacts:
 - path: build\$(configuration)
   name: 'USBqemu-wheel-$(APPVEYOR_BUILD_VERSION)-$(platform)-$(Date)-$(COMMIT_SHA)-$(configuration)'
   type: zip
